# badges.py

# List of specific skill badges
SKILL_BADGES_LIST = [
        "Prompt Design in Vertex AI",
        "Protect Cloud Traffic with BeyondCorp Enterprise (BCE) Security",
        "Manage Kubernetes in Google Cloud",
        "Using the Google Cloud Speech API",
        "Use APIs to Work with Cloud Storage",
        "The Basics of Google Cloud Compute",
        "Streaming Analytics into BigQuery",
        "Secure BigLake Data",
        "Protect Sensitive Data with Data Loss Prevention",
        "Networking Fundamentals on Google Cloud",
        "Monitoring in Google Cloud",
        "Get Started with Pub/Sub",
        "Get Started with Eventarc",
        "Get Started with Dataplex",
        "Get Started with Cloud Storage",
        "Implement DevOps Workflows in Google Cloud",
        "Create a Streaming Data Lake on Cloud Storage",
        "Configure Service Accounts and IAM Roles for Google Cloud",
        "Cloud Speech API: 3 Ways",
        "Cloud Functions: 3 Ways",
        "Build Google Cloud Infrastructure for Azure Professionals",
        "Build Google Cloud Infrastructure for AWS Professionals",
        "Get Started with Google Workspace Tools",
        "App Engine: 3 Ways",
        "Analyze Sentiment with Natural Language API",
        "Deploy Kubernetes Applications on Google Cloud",
        "Get Started with API Gateway",
        "Store, Process, and Manage Data on Google Cloud - Command Line",
        "Store, Process, and Manage Data on Google Cloud - Console",
        "Optimize Costs for Google Kubernetes Engine",
        "Monitor and Manage Google Cloud Resources",
        "Create and Manage Bigtable Instances",
        "Implement Load Balancing on Compute Engine",
        "Get Started with Looker",
        "Cloud Architecture: Design, Implement, and Manage",
        "Build a Website on Google Cloud",
        "Set Up an App Dev Environment on Google Cloud",
        "App Building with AppSheet",
        "Analyze Speech and Language with Google APIs",
        "Analyze Images with the Cloud Vision API",
        "Analyze BigQuery Data in Connected Sheets",
        "Prepare Data for ML APIs on Google Cloud",
        "Use Machine Learning APIs on Google Cloud",
        "Develop your Google Cloud Network",
        "Derive Insights from BigQuery Data",
        "Build Real World AI Applications with Gemini and Imagen",
        "Prompt Design in Vertex AI",
        "Protect Cloud Traffic with BeyondCorp Enterprise (BCE) Security",
        "Manage Kubernetes in Google Cloud",
        "Mitigate Threats and Vulnerabilities with Security Command Center",
        "Using the Google Cloud Speech API",
        "Use APIs to Work with Cloud Storage",
        "The Basics of Google Cloud Compute",
        "Tag and Discover BigLake Data",
        "Streaming Analytics into BigQuery",
        "Secure BigLake Data",
        "Protect Sensitive Data with Data Loss Prevention",
        "Networking Fundamentals on Google Cloud",
        "Monitoring in Google Cloud",
        "Get Started with Pub/Sub",
        "Get Started with Eventarc",
        "Get Started with Dataplex",
        "Get Started with Cloud Storage",
        "Implement DevOps Workflows in Google Cloud",
        "Create a Secure Data Lake on Cloud Storage",
        "Configure Service Accounts and IAM Roles for Google Cloud",
        "Cloud Speech API: 3 Ways",
        "Cloud Functions: 3 Ways",
        "Build Google Cloud Infrastructure for Azure Professionals",
        "Build Google Cloud Infrastructure for AWS Professionals",
        "App Engine: 3 Ways",
        "Analyze Sentiment with Natural Language API",
        "Deploy Kubernetes Applications on Google Cloud",
        "Get Started with API Gateway",
        "Store, Process, and Manage Data on Google Cloud - Command Line",
        "Store, Process, and Manage Data on Google Cloud - Console",
        "Optimize Costs for Google Kubernetes Engine",
        "Monitor and Manage Google Cloud Resources",
        "Create and Manage Bigtable Instances",
        "Implement Load Balancing on Compute Engine",
        "Get Started with Looker",
        "Cloud Architecture: Design, Implement, and Manage",
        "Build a Website on Google Cloud",
        "Set Up an App Dev Environment on Google Cloud",
        "App Building with AppSheet",
        "Analyze Speech and Language with Google APIs",
        "Analyze Images with the Cloud Vision API",
        "Analyze BigQuery Data in Connected Sheets",
        "Prepare Data for ML APIs on Google Cloud",
        "Use Machine Learning APIs on Google Cloud",
        "Develop your Google Cloud Network",
        "Derive Insights from BigQuery Data",
        "Build Real World AI Applications with Gemini and Imagen",
        "Create and Manage Cloud Spanner Instances",
        "Build Infrastructure with Terraform on Google Cloud",
        "Prepare Data for Looker Dashboards and Reports",
        "Engineer Data for Predictive Modeling with BigQuery ML",
        "Build a Data Warehouse with BigQuery",
        "Share Data Using Google Data Cloud",
        "Use Functions, Formulas, and Charts in Google Sheets",
        "Integrate BigQuery Data and Google Workspace using Apps Script",
        "Automate Data Capture at Scale with Document AI",
        "Develop GenAI Apps with Gemini and Streamlit",
        "Prompt Design in Vertex AI",
        "Manage Kubernetes in Google Cloud",
        "Use Functions, Formulas, and Charts in Google Sheets",
        "Mitigate Threats and Vulnerabilities with Security Command Center",
        "The Basics of Google Cloud Compute",
        "Networking Fundamentals on Google Cloud",
        "Monitoring in Google Cloud",
        "Develop Serverless Applications on Cloud Run",
        "Get Started with Pub/Sub",
        "Get Started with Eventarc",
        "Get Started with Dataplex",
        "Get Started with Cloud Storage",
        "Implement DevOps Workflows in Google Cloud",
        "Cloud Speech API: 3 Ways",
        "Cloud Functions: 3 Ways",
        "Get Started with Google Workspace Tools",
        "App Engine: 3 Ways",
        "Deploy Kubernetes Applications on Google Cloud",
        "Get Started with API Gateway",
        "Perform Predictive Data Analysis in BigQuery",
        "Optimize Costs for Google Kubernetes Engine",
        "Build a Secure Google Cloud Network",
        "Manage Data Models in Looker",
        "Develop Serverless Apps with Firebase",
        "Implement Load Balancing on Compute Engine",
        "Get Started with Looker",
        "Classify Images with TensorFlow on Google Cloud",
        "Implement Cloud Security Fundamentals on Google Cloud",
        "Cloud Architecture: Design, Implement, and Manage",
        "Set Up an App Dev Environment on Google Cloud",
        "Build Infrastructure with Terraform on Google Cloud",
        "Analyze Speech and Language with Google APIs",
        "Analyze Images with the Cloud Vision API",
        "Prepare Data for ML APIs on Google Cloud",
        "Use Machine Learning APIs on Google Cloud",
        "Engineer Data for Predictive Modeling with BigQuery ML",
        "Create ML Models with BigQuery ML",
        "Develop your Google Cloud Network",
        "Build a Data Warehouse with BigQuery",
        "Derive Insights from BigQuery Data"

]

# Cloud Digital Leader badges
CLOUD_DIGITAL_LEADER_BADGES = [
    "Scaling with Google Cloud Operations",
    "Trust and Security with Google Cloud",
    "Modernize Infrastructure and Applications with Google Cloud",
    "Innovating with Google Cloud Artificial Intelligence",
    "Exploring Data Transformation with Google Cloud",
    "Digital Transformation with Google Cloud"
]
