# badges.py

# List of specific skill badges
SKILL_BADGES_LIST = [
    'Detect Manufacturing Defects using Visual Inspection AI', 'Streaming Analytics into BigQuery',
    'Configure Service Accounts and IAM Roles for Google Cloud', 'Optimize Costs for Google Kubernetes Engine', 
    'Manage Kubernetes in Google Cloud', 'Set Up a Google Cloud Network', 
    'Prepare Data for ML APIs on Google Cloud ', 'Tag and Discover BigLake Data',
    'Store, Process, and Manage Data on Google Cloud - Console', 
    'Build Infrastructure with Terraform on Google Cloud', 'Create and Manage Bigtable Instances',
    'Using the Google Cloud Speech API', 'Build a Data Mesh with Dataplex', 
    'Create and Manage Cloud Spanner Instances', 'Create ML Models with BigQuery ML', 
    'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG', 
    'Build a Data Warehouse with BigQuery', 'Get Started with Dataplex', 'Build Google Cloud Infrastructure for Azure Professionals',
      'Build Google Cloud Infrastructure for AWS Professionals',
        'Get Started with Looker', 'Prompt Design in Vertex AI', 
        'Get Started with Eventarc', 'Build Real World AI Applications with Gemini and Imagen',
          'Develop Serverless Applications on Cloud Run',
            'Store, Process, and Manage Data on Google Cloud - Command Line', 
            'Implement DevOps Workflows in Google Cloud', 
            'Build LangChain Applications using Vertex AI',
              'Use Functions, Formulas, and Charts in Google Sheets',
                'Classify Images with TensorFlow on Google Cloud',
                  'Implement CI/CD Pipelines on Google Cloud', 
                  'Analyze Images with the Cloud Vision API', 'Deploy and Manage Apigee X', 
                  'Analyze Speech and Language with Google APIs', 'App Building with AppSheet', 
                  'Cloud Architecture: Design, Implement, and Manage', 'Use APIs to Work with Cloud Storage', 
                  'Engineer Data for Predictive Modeling with BigQuery ML', 'Build and Deploy Machine Learning Solutions on Vertex AI', 
                  'Create and Manage AlloyDB Databases', 'Get Started with Pub/Sub', 'The Basics of Google Cloud Compute',
                    'Implement Load Balancing on Compute Engine', 'Mitigate Threats and Vulnerabilities with Security Command Center', 
                    'Derive Insights from BigQuery Data', 'Share Data Using Google Data Cloud',
                                           'Integrate BigQuery Data and Google Workspace using Apps Script', 'Create and Manage AlloyDB Instances', 
                                           'Get Started with Cloud Storage', 
                                           'Create a Streaming Data Lake on Cloud Storage',
                                             'Google Workspace for Education', 
                                           
                                           'Migrate MySQL data to Cloud SQL using Database Migration Service', 'Create a Secure Data Lake on Cloud Storage', 
                                           'Perform Predictive Data Analysis in BigQuery', 'Networking Fundamentals on Google Cloud', 
                                           'Use Machine Learning APIs on Google Cloud', 'Prepare Data for ML APIs on Google Cloud', 
                                           'Develop Serverless Apps with Firebase', 'Deploy Kubernetes Applications on Google Cloud', 
                                           'Automate Data Capture at Scale with Document AI', 'Get Started with Google Workspace Tools',
                                             'Cloud Speech API: 3 Ways', 'Build a Secure Google Cloud Network', 'Monitoring in Google Cloud',
                                               'Monitor and Log with Google Cloud Observability', 'Implement Cloud Security Fundamentals on Google Cloud',
                                                 'Monitor and Manage Google Cloud Resources', 'Protect Sensitive Data with Data Loss Prevention',
                                                   'Explore Generative AI with the Vertex AI Gemini API', 
                                                   'Protect Cloud Traffic with BeyondCorp Enterprise (BCE) Security',
                                                     'Create and Manage Cloud SQL for PostgreSQL Instances',
                                                       'Set Up an App Dev Environment on Google Cloud', 'Build a Website on Google Cloud',

                                                         'Analyze BigQuery Data in Connected Sheets', 'Generative AI Fundamentals - Locales', 
                                                         'Prepare Data for Looker Dashboards and Reports', 'Cloud Functions: 3 Ways',
                                                           'Get Started with API Gateway', 'Analyze Sentiment with Natural Language API', 
                                                           'Develop with Apps Script and AppSheet', 'Build LookML Objects in Looker', 'Secure BigLake Data', 
                                                           'Monitor Environments with Google Cloud Managed Service for Prometheus', 'Manage Data Models in Looker',
                                                             'App Engine: 3 Ways', 'Develop your Google Cloud Network',
                                                    'Develop GenAI Apps with Gemini and Streamlit']

# Cloud Digital Leader badges
CLOUD_DIGITAL_LEADER_BADGES = [
    "Scaling with Google Cloud Operations",
    "Trust and Security with Google Cloud",
    "Modernize Infrastructure and Applications with Google Cloud",
    "Innovating with Google Cloud Artificial Intelligence",
    "Exploring Data Transformation with Google Cloud",
    "Digital Transformation with Google Cloud",
    "Get Started with Sensitive Data Protection",
]
