# badges.py

# List of specific skill badges
SKILL_BADGES_LIST_OLD = [
    'Implementing Cloud Load Balancing for Compute Engine',
    'Analyze BigQuery Data in Connected Sheets',
    'Analyze Images with the Cloud Vision API',
    'Analyze Sentiment with Natural Language API',
    'Analyze Speech and Language with Google APIs',
    'App Building with AppSheet',
    'App Engine: 3 Ways',
    'Automate Data Capture at Scale with Document AI',
    'Begin with Workspace: Essentials',
    'Build a Data Mesh with Dataplex',
    'Build a Data Warehouse with BigQuery',
    'Build a Secure Google Cloud Network',
    'Build a Website on Google Cloud',
    'Build and Deploy Machine Learning Solutions on Vertex AI',
    'Build Google Cloud Infrastructure for AWS Professionals',
    'Build Google Cloud Infrastructure for Azure Professionals',
    'Build Infrastructure with Terraform on Google Cloud',
    'Build LookML Objects in Looker',
    'Build Real World AI Applications with Gemini and Imagen',
    'Classify Images with TensorFlow on Google Cloud',
    'Cloud Architecture: Design, Implement, and Manage',
    'Cloud Functions: 3 Ways',
    'Cloud Speech API: 3 Ways',
    'Configure Service Accounts and IAM Roles for Google Cloud',
    'Create a Secure Data Lake on Cloud Storage',
    'Create a Streaming Data Lake on Cloud Storage',
    'Create and Manage AlloyDB Instances',
    'Create and Manage Bigtable Instances',
    'Create and Manage Cloud Spanner Instances',
    'Create and Manage Cloud SQL for PostgreSQL Instances',
    'Create ML Models with BigQuery ML',
    'Deploy and Manage Apigee X',
    'Deploy Kubernetes Applications on Google Cloud',
    'Derive Insights from BigQuery Data',
    'Detect Manufacturing Defects using Visual Inspection AI',
    'Develop and Secure APIs with Apigee X',
    'Develop GenAI Apps with Gemini and Streamlit',
    'Develop Serverless Applications on Cloud Run',
    'Develop Serverless Apps with Firebase',
    'Develop with Apps Script and AppSheet',
    'Develop your Google Cloud Network',
    'Engineer Data for Predictive Modeling with BigQuery ML',
    'Explore Generative AI with the Vertex AI Gemini API',
    'Generative AI Fundamentals - Locales',
    'Get Started with API Gateway',
    'Get Started with Cloud Storage',
    'Get Started with Dataplex',
    'Get Started with Eventarc',
    'Get Started with Google Workspace Tools',
    'Get Started with Looker',
    'Get Started with Pub/Sub',
    'Get Started with Sensitive Data Protection',
    'Get Started with TensorFlow on Google Cloud',
    'Google Workspace for Education',
    'Implement CI/CD Pipelines on Google Cloud',
    'Implement Cloud Security Fundamentals on Google Cloud',
    'Implement DevOps Workflows in Google Cloud',
    'Implement Load Balancing on Compute Engine',
    'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG',
    'Integrate BigQuery Data and Google Workspace using Apps Script',
    'Manage Data Models in Looker',
    'Manage Kubernetes in Google Cloud',
    'Migrate MySQL data to Cloud SQL using Database Migration Service',
    'Mitigate Threats and Vulnerabilities with Security Command Center',
    'Monitor and Log with Google Cloud Observability',
    'Monitor and Manage Google Cloud Resources',
    'Monitor Environments with Google Cloud Managed Service for Prometheus',
    'Monitoring in Google Cloud',
    'Networking Fundamentals on Google Cloud',
    'Optimize Costs for Google Kubernetes Engine',
    'Perform Predictive Data Analysis in BigQuery',
    'Prepare Data for Looker Dashboards and Reports',
    'Prepare Data for ML APIs on Google Cloud',
    'Prompt Design in Vertex AI',
    'Protect Cloud Traffic with BeyondCorp Enterprise (BCE) Security',
    'Protect Sensitive Data with Data Loss Prevention',
    'Secure BigLake Data',
    'Secure Software Delivery',
    'Set Up a Google Cloud Network',
    'Set Up an App Dev Environment on Google Cloud',
    'Share Data Using Google Data Cloud',
    'Store, Process, and Manage Data on Google Cloud - Command Line',
    'Store, Process, and Manage Data on Google Cloud - Console',
    'Streaming Analytics into BigQuery',
    'Tag and Discover BigLake Data',
    'The Basics of Google Cloud Compute',
    'Use APIs to Work with Cloud Storage',
    'Use Functions, Formulas, and Charts in Google Sheets',
    'Use Machine Learning APIs on Google Cloud',
    'Using the Google Cloud Speech API',
    'Protect Cloud Traffic with Chrome Enterprise Premium Security',
    'Cloud Run Functions: 3 Ways',
    'Explore Generative AI with the Gemini API in Vertex AI',
    'Discover and Protect Sensitive Data Across Your Ecosystem',
    'Build Custom Processors with Document AI',  
]
SKILL_BADGES_LIST = [
    'Manage Kubernetes in Google Cloud',
    'Classify Images with TensorFlow on Google Cloud',
    'Derive Insights from BigQuery Data',
    'Share Data Using Google Data Cloud',
    'Get Started with Google Workspace Tools',
    'Migrate MySQL data to Cloud SQL using Database Migration Service',
    'Use Machine Learning APIs on Google Cloud',
    'Mitigate Threats and Vulnerabilities with Security Command Center',
    'Monitor Environments with Google Cloud Managed Service for Prometheus',
    'Get Started with Dataplex',
    'Deploy Kubernetes Applications on Google Cloud',
    'Prepare Data for ML APIs on Google Cloud',
    'Set Up an App Dev Environment on Google Cloud',
    'Develop your Google Cloud Network',
    'Implementing Cloud Load Balancing for Compute Engine',
    'Build a Website on Google Cloud',
    'Cloud Architecture: Design, Implement, and Manage',
    'Build a Secure Google Cloud Network',
    'Engineer Data for Predictive Modeling with BigQuery ML',
    'Implement DevOps Workflows in Google Cloud',
    'Monitor and Log with Google Cloud Observability',
    'Create ML Models with BigQuery ML',
    'Build a Data Warehouse with BigQuery',
    'Implement Cloud Security Fundamentals on Google Cloud',
    'Develop Serverless Applications on Cloud Run',
    'Develop Serverless Apps with Firebase',
    'Optimize Costs for Google Kubernetes Engine',
    'Prepare Data for Looker Dashboards and Reports',
    'Deploy and Manage Apigee X',
    'Build and Deploy Machine Learning Solutions on Vertex AI',
    'Create and Manage Cloud SQL for PostgreSQL Instances',
    'Build LookML Objects in Looker',
    'Develop and Secure APIs with Apigee X',
    'Manage Data Models in Looker',
    'Detect Manufacturing Defects using Visual Inspection AI',
    'Automate Data Capture at Scale with Document AI',
    'Perform Predictive Data Analysis in BigQuery',
    'Build Infrastructure with Terraform on Google Cloud',
    'Create and Manage Cloud Spanner Instances',
    'Use Functions, Formulas, and Charts in Google Sheets',
    'Implement CI/CD Pipelines on Google Cloud',
    'Create and Manage Bigtable Instances',
    'Build Google Cloud Infrastructure for AWS Professionals',
    'Build Google Cloud Infrastructure for Azure Professionals',
    'Store, Process, and Manage Data on Google Cloud - Command Line',
    'Monitor and Manage Google Cloud Resources',
    'Analyze BigQuery Data in Connected Sheets',
    'Store, Process, and Manage Data on Google Cloud - Console',
    'Get Started with Looker',

    'App Building with AppSheet',
    'Get Started with API Gateway',
    'Streaming Analytics into BigQuery',
    'Cloud Run Functions: 3 Ways',
    'Create a Streaming Data Lake on Cloud Storage',
    'Get Started with Cloud Storage',
    'App Engine: 3 Ways',
    'Get Started with Eventarc',
    'Monitoring in Google Cloud',
    'Analyze Speech and Language with Google APIs',
    'Create a Secure Data Lake on Cloud Storage',
    'Tag and Discover BigLake Data',
    'Secure BigLake Data',
    'Analyze Images with the Cloud Vision API',
    'Get Started with Sensitive Data Protection',
    'DEPRECATED Networking Fundamentals on Google Cloud',
    'The Basics of Google Cloud Compute',
    'Use APIs to Work with Cloud Storage',
    'Using the Google Cloud Speech API',
    'Develop with Apps Script and AppSheet',
    'Analyze Sentiment with Natural Language API',
    'Build a Data Mesh with Dataplex',
    'Cloud Speech API: 3 Ways',
    'Integrate BigQuery Data and Google Workspace using Apps Script',
    'Configure Service Accounts and IAM Roles for Google Cloud',
    'Build Custom Processors with Document AI',
    'Explore Generative AI with the Gemini API in Vertex AI',
    'Develop GenAI Apps with Gemini and Streamlit',
    'Inspect Rich Documents with Gemini Multimodality and Multimodal RAG',
    'Build Real World AI Applications with Gemini and Imagen',
    'Create and Manage AlloyDB Instances',
    'Set Up a Google Cloud Network',
    'Secure Software Delivery',
    'Get Started with Pub/Sub',
    'Protect Cloud Traffic with Chrome Enterprise Premium Security',
    'Prompt Design in Vertex AI',
    'Discover and Protect Sensitive Data Across Your Ecosystem',
    'Implement Multimodal Vector Search with BigQuery',
    'Enhance Gemini Model Capabilities',
    'Privileged Access with IAM',
    'Connecting Cloud Networks with NCC'
]

# Cloud Digital Leader badges
CLOUD_DIGITAL_LEADER_BADGES = [
    "Scaling with Google Cloud Operations",
    "Trust and Security with Google Cloud",
    "Modernize Infrastructure and Applications with Google Cloud",
    "Innovating with Google Cloud Artificial Intelligence",
    "Exploring Data Transformation with Google Cloud",
    "Digital Transformation with Google Cloud",
    
]
# # Arcade Classroom badges
Arcade_Classroom =[
    "Webhook Fundamentals",
    "Advanced Webhook Concepts",
    "Basic Performance Measurement",
    "Advanced Performance Measurement",
    "CCAI Frontend Integrations",
    "CCAI Architecture",
    "Conversation Design Fundamentals",
    "Advanced Conversation Design",
]
LAB_FREE_COURSES = [
    'Responsible AI: Applying AI Principles with Google Cloud',
    'Responsible AI for Digital Leaders with Google Cloud',
    'Customer Experience with Google AI Architecture',
    'Machine Learning Operations (MLOps) with Vertex AI: Model Evaluation',
    'Conversational AI on Vertex AI and Dialogflow CX',
    'Building Complex End to End Self-Service Experiences in Dialogflow CX',
    'Google Drive',
    'Google Docs',
    'Google Slides',
    'Google Meet',
    'Google Sheets',
    'Google Calendar',
    'Digital Transformation with Google Cloud',
    'Exploring Data Transformation with Google Cloud',
    'Infrastructure and Application Modernization with Google Cloud',
    'Scaling with Google Cloud Operations',
    'Innovating with Google Cloud Artificial Intelligence',
    'Modernize Infrastructure and Applications with Google Cloud',
    'Gen AI: Beyond the Chatbot',
    'Gen AI: Unlock Foundational Concepts',
    'Gen AI: Navigate the Landscape',
    'Gen AI Apps: Transform Your Work',
    'Gen AI Agents: Transform Your Organization',
    'AI Infrastructure: Introduction to AI Hypercomputer',
    'Introduction to Large Language Models',
    'Trust and Security with Google Cloud'
]
